// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ValleyClient is the client API for Valley service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ValleyClient interface {
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
}

type valleyClient struct {
	cc grpc.ClientConnInterface
}

func NewValleyClient(cc grpc.ClientConnInterface) ValleyClient {
	return &valleyClient{cc}
}

func (c *valleyClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, "/pb.Valley/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ValleyServer is the server API for Valley service.
// All implementations must embed UnimplementedValleyServer
// for forward compatibility
type ValleyServer interface {
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
	mustEmbedUnimplementedValleyServer()
}

// UnimplementedValleyServer must be embedded to have forward compatible implementations.
type UnimplementedValleyServer struct {
}

func (UnimplementedValleyServer) Echo(context.Context, *EchoRequest) (*EchoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedValleyServer) mustEmbedUnimplementedValleyServer() {}

// UnsafeValleyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ValleyServer will
// result in compilation errors.
type UnsafeValleyServer interface {
	mustEmbedUnimplementedValleyServer()
}

func RegisterValleyServer(s grpc.ServiceRegistrar, srv ValleyServer) {
	s.RegisterService(&Valley_ServiceDesc, srv)
}

func _Valley_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValleyServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Valley/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValleyServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Valley_ServiceDesc is the grpc.ServiceDesc for Valley service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Valley_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Valley",
	HandlerType: (*ValleyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _Valley_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "valley.proto",
}
